- hosts: 192.168.1.100
  user: iizuka
  become: yes
  tasks:
    - name: docker is installed
      yum:
        name: docker
        state: installed

    - name: docker service is started
      systemd:
        name: docker
        state: started

    - name: docker service is enabled
      systemd:
        name: docker
        enabled: yes
        masked: no

    - name: add user to dockerroot group
      user:
        name: iizuka
        groups: dockerroot
        append: yes

    - name: chown /var/run/docker.sock
      file:
        path: /var/run/docker.sock
        owner: root
        group: dockerroot

    - name: add options
      lineinfile: >
        dest=/etc/sysconfig/docker
        line="OPTIONS='--insecure-registry=192.168.1.0/24 --selinux-enabled --log-driver=journald -G dockerroot'"

